server.port=8085
spring.application.name=matching-engine

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
orderflow.kafka.topic.trade-executions=trade.executions
orderflow.kafka.topic.order-book-updates=order.book.updates